dist: xenial
sudo: false
language: cpp

before_install:
  - export BUILD_DIR=$TRAVIS_BUILD_DIR/build
  - sudo apt-get -y -qq update
  - sudo apt-get install -y -qq zlib1g-dev libexpat1-dev libssl-dev libzmq3-dev libgtk-3-dev libwebkit2gtk-4.0-dev libgsoap-dev
  - pip install --user cpp-coveralls
  - git clone https://github.com/zeromq/cppzmq.git
  - cd cppzmq && mkdir build && cmake .. && sudo make -j4 install

after_success:
  - coveralls --build . --root .. --include "src" --gcov-options "-lbc" --exclude-pattern ".*CMakeFiles.*"

script:
  - mkdir -p $BUILD_DIR && cd $BUILD_DIR
  - cmake -DCOVERAGE=ON -DLONGLONG=ON -DCMAKE_BUILD_TYPE=C++11=ON ..
  - make
