dist: xenial
sudo: required
language: cpp

before_install:
  - export BUILD_DIR=$TRAVIS_BUILD_DIR/build
  - sudo apt-get -y -qq update
  - sudo apt-get install -y -qq zlib1g-dev libexpat1-dev libssl-dev libzmqpp-dev libgtk-3-dev libwebkit2gtk-4.0-dev libgsoap-dev
  - pip install --user cpp-coveralls
  - mkdir -p $BUILD_DIR && cd $BUILD_DIR

after_success:
  - coveralls --build . --root .. --include "src" --gcov-options "-lbc" --exclude-pattern ".*CMakeFiles.*"

script:
  - cmake -DCOVERAGE=ON -DLONGLONG=ON -DCMAKE_BUILD_TYPE=C++11=ON ..
  - make
