/* soapxmdsBindingProxy.h
   Generated by gSOAP 2.8.61 for xibo.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapxmdsBindingProxy_H
#define soapxmdsBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC xmdsBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'xmdsBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in xibo.h, if any
        /// Construct a proxy with new managing context
        xmdsBindingProxy();
        /// Copy constructor
        xmdsBindingProxy(const xmdsBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        xmdsBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        xmdsBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        xmdsBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        xmdsBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        xmdsBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~xmdsBindingProxy();
        /// Initializer used by constructors
        virtual void xmdsBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual xmdsBindingProxy *copy();
        /// Copy assignment
        xmdsBindingProxy& operator=(const xmdsBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'RegisterDisplay' (returns SOAP_OK or error code)
        virtual int RegisterDisplay(const std::string& serverKey, const std::string& hardwareKey, const std::string& displayName, const std::string& clientType, const std::string& clientVersion, int clientCode, const std::string& operatingSystem, const std::string& macAddress, const std::string& xmrChannel, const std::string& xmrPubKey, std::string &ActivationMessage)
        { return this->RegisterDisplay(NULL, NULL, serverKey, hardwareKey, displayName, clientType, clientVersion, clientCode, operatingSystem, macAddress, xmrChannel, xmrPubKey, ActivationMessage); }
        virtual int RegisterDisplay(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, const std::string& displayName, const std::string& clientType, const std::string& clientVersion, int clientCode, const std::string& operatingSystem, const std::string& macAddress, const std::string& xmrChannel, const std::string& xmrPubKey, std::string &ActivationMessage);
        /// Web service operation 'RequiredFiles' (returns SOAP_OK or error code)
        virtual int RequiredFiles(const std::string& serverKey, const std::string& hardwareKey, std::string &RequiredFilesXml)
        { return this->RequiredFiles(NULL, NULL, serverKey, hardwareKey, RequiredFilesXml); }
        virtual int RequiredFiles(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, std::string &RequiredFilesXml);
        /// Web service operation 'GetFile' (returns SOAP_OK or error code)
        virtual int GetFile(const std::string& serverKey, const std::string& hardwareKey, int fileId, const std::string& fileType, double chunkOffset, double chuckSize, xsd__base64Binary &file)
        { return this->GetFile(NULL, NULL, serverKey, hardwareKey, fileId, fileType, chunkOffset, chuckSize, file); }
        virtual int GetFile(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, int fileId, const std::string& fileType, double chunkOffset, double chuckSize, xsd__base64Binary &file);
        /// Web service operation 'Schedule' (returns SOAP_OK or error code)
        virtual int Schedule(const std::string& serverKey, const std::string& hardwareKey, std::string &ScheduleXml)
        { return this->Schedule(NULL, NULL, serverKey, hardwareKey, ScheduleXml); }
        virtual int Schedule(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, std::string &ScheduleXml);
        /// Web service operation 'BlackList' (returns SOAP_OK or error code)
        virtual int BlackList(const std::string& serverKey, const std::string& hardwareKey, int mediaId, const std::string& type, const std::string& reason, bool &success)
        { return this->BlackList(NULL, NULL, serverKey, hardwareKey, mediaId, type, reason, success); }
        virtual int BlackList(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, int mediaId, const std::string& type, const std::string& reason, bool &success);
        /// Web service operation 'SubmitLog' (returns SOAP_OK or error code)
        virtual int SubmitLog(const std::string& serverKey, const std::string& hardwareKey, const std::string& logXml, bool &success)
        { return this->SubmitLog(NULL, NULL, serverKey, hardwareKey, logXml, success); }
        virtual int SubmitLog(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, const std::string& logXml, bool &success);
        /// Web service operation 'SubmitStats' (returns SOAP_OK or error code)
        virtual int SubmitStats(const std::string& serverKey, const std::string& hardwareKey, const std::string& statXml, bool &success)
        { return this->SubmitStats(NULL, NULL, serverKey, hardwareKey, statXml, success); }
        virtual int SubmitStats(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, const std::string& statXml, bool &success);
        /// Web service operation 'MediaInventory' (returns SOAP_OK or error code)
        virtual int MediaInventory(const std::string& serverKey, const std::string& hardwareKey, const std::string& mediaInventory, bool &success)
        { return this->MediaInventory(NULL, NULL, serverKey, hardwareKey, mediaInventory, success); }
        virtual int MediaInventory(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, const std::string& mediaInventory, bool &success);
        /// Web service operation 'GetResource' (returns SOAP_OK or error code)
        virtual int GetResource(const std::string& serverKey, const std::string& hardwareKey, int layoutId, const std::string& regionId, const std::string& mediaId, std::string &resource)
        { return this->GetResource(NULL, NULL, serverKey, hardwareKey, layoutId, regionId, mediaId, resource); }
        virtual int GetResource(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, int layoutId, const std::string& regionId, const std::string& mediaId, std::string &resource);
        /// Web service operation 'NotifyStatus' (returns SOAP_OK or error code)
        virtual int NotifyStatus(const std::string& serverKey, const std::string& hardwareKey, const std::string& status, bool &success)
        { return this->NotifyStatus(NULL, NULL, serverKey, hardwareKey, status, success); }
        virtual int NotifyStatus(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, const std::string& status, bool &success);
        /// Web service operation 'SubmitScreenShot' (returns SOAP_OK or error code)
        virtual int SubmitScreenShot(const std::string& serverKey, const std::string& hardwareKey, const xsd__base64Binary& screenShot, bool &success)
        { return this->SubmitScreenShot(NULL, NULL, serverKey, hardwareKey, screenShot, success); }
        virtual int SubmitScreenShot(const char *soap_endpoint, const char *soap_action, const std::string& serverKey, const std::string& hardwareKey, const xsd__base64Binary& screenShot, bool &success);
    };
#endif
